#!/bin/bash
# Generated by dsh-super-injector dev_scaffold_plugin (adapted for npm-installed dsh).
# Build: compile src/ → lib/ with tsc; link peer deps as node_modules junctions.
# DSH_CHECKOUT 探测优先级:
#   1. 环境变量 DSH_CHECKOUT
#   2. 源码 checkout: $HOME/dsh-harness / $HOME/dsh / $HOME/.dsh/dsh-harness（含 packages/）
#   3. npm 全局安装的 dsh（node_modules/@deepseek-ai/dsh，嵌套 node_modules 里有全部 peer）
# tsc 优先用 checkout 的，回退插件本地 node_modules/.bin/tsc（npm install 装好）。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# ── 定位 dsh 包根（源码 checkout 或 npm 安装目录） ─────────────────────────────
dsh_root() {
  local c="${DSH_CHECKOUT:-}"
  if [ -n "$c" ] && { [ -d "$c/packages" ] || [ -d "$c/node_modules/@deepseek-ai/cordis" ]; }; then
    echo "$c"; return
  fi
  for candidate in "$HOME/dsh-harness" "$HOME/dsh" "$HOME/.dsh/dsh-harness"; do
    if [ -d "$candidate/packages" ]; then echo "$candidate"; return; fi
  done
  # npm 安装：从本插件目录向上找不到，直接探测常见 npm 全局前缀
  for candidate in "$HOME/AppData/Roaming/npm/node_modules/@deepseek-ai/dsh" \
                   "/usr/local/lib/node_modules/@deepseek-ai/dsh" \
                   "/usr/lib/node_modules/@deepseek-ai/dsh"; do
    if [ -d "$candidate/node_modules/@deepseek-ai/cordis" ]; then echo "$candidate"; return; fi
  done
  echo ""
}

DSH="$(dsh_root)"
if [ -z "$DSH" ]; then
  echo "build: cannot locate dsh packages (set DSH_CHECKOUT)" >&2
  exit 1
fi
echo "=== Using dsh packages at: $DSH"

# 源码 checkout（packages/ 存在）→ vendor/packages 相对路径；npm 安装 → 嵌套 node_modules
if [ -d "$DSH/packages" ]; then
  PKG_CORDIS="vendor/cordis"
  PKG_COSMOKIT="vendor/cosmokit"
  PKG_SCHEMASTERY="vendor/schemastery"
  PKG_TOOLS="packages/core/tools"
  PKG_FS="packages/core/fs"
else
  PKG_CORDIS="node_modules/@deepseek-ai/cordis"
  PKG_COSMOKIT="node_modules/@deepseek-ai/cosmokit"
  PKG_SCHEMASTERY="node_modules/@deepseek-ai/schemastery"
  PKG_TOOLS="node_modules/@deepseek-ai/dsh-tools"
  PKG_FS="node_modules/@deepseek-ai/dsh-fs"
fi

link_pkg() {
  local target="$DSH/$2"
  if [ ! -e "$target" ]; then
    echo "build: dependency target missing: $target" >&2
    exit 1
  fi
  node -e "
    const fs = require('fs');
    const path = require('path');
    const link = path.resolve(process.argv[1]);
    const target = path.resolve(process.argv[2]);
    fs.rmSync(link, { recursive: true, force: true });
    fs.mkdirSync(path.dirname(link), { recursive: true });
    fs.symlinkSync(target, link, process.platform === 'win32' ? 'junction' : 'dir');
  " "node_modules/$1" "$target"
}

echo "=== Linking build dependencies ==="
mkdir -p node_modules/@deepseek-ai
node -e "const fs=require('fs');fs.rmSync('node_modules/@standard-schema',{recursive:true,force:true})"
link_pkg cordis "$PKG_CORDIS"
link_pkg cosmokit "$PKG_COSMOKIT"
link_pkg @deepseek-ai/dsh-tools "$PKG_TOOLS"
link_pkg @deepseek-ai/dsh-fs "$PKG_FS"
# @types/node（编译类型；checkout 自带则链接，否则用本地 devDependencies）
if [ -d "$DSH/node_modules/@types/node" ]; then
  link_pkg @types/node node_modules/@types/node
fi

# ── tsc：checkout 优先，本地回退 ───────────────────────────────────────────────
TSC=""
for candidate in "$DSH/node_modules/.bin/tsc" "$ROOT/node_modules/.bin/tsc"; do
  if [ -x "$candidate" ] || [ -f "$candidate" ] || [ -f "$candidate.cmd" ]; then TSC="$candidate"; break; fi
done
if [ -z "$TSC" ]; then
  echo "build: tsc not found (run 'npm install' in the plugin dir, or point DSH_CHECKOUT at a checkout with typescript)" >&2
  exit 1
fi

echo "=== Compiling src → lib ==="
"$TSC" -p tsconfig.json
echo "=== Build complete ==="
